config/routes.rb
TextMe::Application.routes.draw do

  root :to => "home#index"

  resources :messages

  resources :locations

end

app/models/destination.rb
class Destination < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :zip_code, format: { with: /\A\d{5}(-\d{4})?\z/, message: "Only valid US Zip Codes allowed" }
  validates :street, length: { in: 1..200, too_long: "Address must be less than 200 letters.", too_short: "Address must be at least 1 letter." }
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :phone_number, presence: true
  # TODO scope :queued, -> { where(sent: false)}

  after_save :dispatch

  private

    def dispatch
      self.dispatch_on = Time.now + t_minus_five_minutes(self.drive_time)
      Resque.enqueue_at(self.dispatch_on, DispatchMessage, self.phone_number)
    end

    def t_minus_five_minutes(time)
      ((time - 300) > 0) ? (time - 300) : 0
    end

end

app/models/number.rb
class Number < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  after_action :allow_iframe

  def index
  end

private

  def allow_iframe
    response.headers['X-Frame-Options'] = 'ALLOW-FROM localhost'
  end

end 

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # before_action :set_location, only: [:show, :edit, :update, :destroy]
  respond_to :json

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    @location.save
    respond_with(@location)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:zip_code, :street, :lat_long, :latitude, :longitude, :gmaps)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # before_action :set_message, only: [:show, :edit, :update, :destroy]
  respond_to :json

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.save
    respond_with(@message)
  end

  private

    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:ip_address, :phone_number, :drive_time)
    end
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/numbers_helper.rb
module NumbersHelper
end

app/views/home/_forms.haml
.panel.panel-primary#destination
  .panel-heading
    %span.big.label.label-success 1
    %h1 What is your destination?
  .panel-body
    =form_for Location.new, :html => { :class => 'form-horizontal destination' }, remote: true do |f|
      .form-group
        =f.label :street, class: "col-sm-2 control-label input-lg", :'data-placement' => 'top', :'data-html' => 'false', :'data-trigger' => 'manual'
        .col-sm-10
          =f.text_field :street, placeholder: "Address", class: 'form-control input-lg address', :'data-required' => 'required', :'data-notblank' => "true", :'data-required-message' => "You must include an address.", :'data-notblank-message' => "Please type a valid US Address."
      .form-group
        =f.label :zip_code, class: "col-sm-2 control-label input-lg", :'data-placement' => 'bottom', :'data-html' => 'false', :'data-trigger' => 'manual'
        .col-sm-10
          =f.text_field :zip_code, placeholder: "Zip Code", class: 'form-control input-lg zip', :'data-required' => 'required', :'data-notblank' => "true", :'data-regex' => "/\A\d{5}(-\d{4})?\z/", :'data-required-message' => "You must include a zip code.", :'data-notblank-message' => "Please type a valid US zip code in the format 55555.", :'data-regex-message' => "Please type a valid US zip code in the format 55555."
        .col-md-offset-2.col-xs-10
          %h3
            %span.city.label.label-success CITY
            %span.state.label.label-success STATE
      .form-group
        .col-md-offset-2.col-xs-10
          =f.submit "Continue", class: "btn btn-default btn-lg"

.panel.panel-primary#origin
  .panel-heading
    %span.big.label.label-success 2
    %h1 Where are you now?
  .panel-body
    =form_for Location.new, :html => { :class => 'form-horizontal origin' }, remote: true do |f|
      .form-group
        =f.label :street, class: "col-md-2 control-label input-lg", :'data-placement' => 'top', :'data-html' => 'false', :'data-trigger' => 'manual'
        .col-md-10
          =f.text_field :street, placeholder: "Address", class: 'form-control input-lg address', :'data-required' => 'required', :'data-notblank' => "true", :'data-required-message' => "You must include an address.", :'data-notblank-message' => "Please type a valid US Address."
      .form-group
        =f.label :zip_code, class: "col-md-2 control-label input-lg", :'data-placement' => 'bottom', :'data-html' => 'false', :'data-trigger' => 'manual'
        .col-md-10
          =f.text_field :zip_code, placeholder: "Zip Code", class: 'form-control input-lg zip', :'data-required' => 'required', :'data-notblank' => "true", :'data-regex' => "/\A\d{5}(-\d{4})?\z/", :'data-required-message' => "You must include a zip code.", :'data-notblank-message' => "Please type a valid US zip code in the format 55555.", :'data-regex-message' => "Please type a valid US zip code in the format 55555."
        .col-md-offset-2.col-md-10
          %h3
            %span.city.label.label-success CITY
            %span.state.label.label-success STATE
      .form-group
        .col-md-offset-2.col-md-10
          =f.submit "Continue", class: "btn btn-default btn-lg"

.panel.panel-primary#message
  .panel-heading
    %span.big.label.label-success 3
    %h1 Who do you want to text when you're almost there?
  .panel-body
    =form_for Message.new, :html => { :class => 'form-horizontal message' }, remote: true do |f|
      .form-group
        =f.label :phone_number, class: "col-md-2 control-label input-lg", :'data-placement' => 'bottom', :'data-html' => 'false', :'data-trigger' => 'manual'
        .col-md-10
          =f.text_field :phone_number, placeholder: "Phone Number", class: 'form-control input-lg', :'data-required' => 'required', :'data-notblank' => "true", :'data-required-message' => "You must include a cell phone number.", :'data-notblank-message' => "Please type a valid US cell phone number."
          =f.hidden_field :drive_time, class: 'drive_time'
      .form-group
        .col-md-offset-2.col-md-10
          =f.submit "Queue Message", class: "btn btn-default btn-lg"

app/views/home/_header.haml
%nav.navbar.navigation{role: 'navigation'}
  %h1.nav-brand.pull-left
    triptext
  %ul.nav.nav-pills.pull-right
    %li
      =link_to "new trip", '#', class: 'active'
    %li
      =link_to "about", '#'
    %li.disabled
      =link_to "log in", '#'

app/views/home/_map.haml
.map
  #panel
  #directions-panel
  #map_canvas

app/views/home/index.haml
= render 'forms'
= render 'map'

app/views/layouts/application.haml
!!!
%html
  %head
    %title triptext // saving lives one text at a time
    = csrf_meta_tags
    %meta{:name => "viewport", :content => "width=device-width"}
  %body
    = render 'header'
    .content
      = yield

  %footer
    %script{:src => "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/locations/_form.html.haml
= form_for @location do |f|
  - if @location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@location.errors.count, "error")} prohibited this location from being saved:"
      %ul
        - @location.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :zip_code
    = f.text_field :zip_code
  .field
    = f.label :lat_long
    = f.text_field :lat_long
  .field
    = f.label :street
    = f.text_field :street
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .field
    = f.label :gmaps
    = f.check_box :gmaps
  .actions
    = f.submit 'Save'

app/views/locations/edit.html.haml
%h1 Editing location

= render 'form'

= link_to 'Show', @location
\|
= link_to 'Back', locations_path

app/views/locations/index.html.haml
%h1 Listing locations

%table
  %tr
    %th Zip code
    %th Lat long
    %th Street
    %th Latitude
    %th Longitude
    %th Gmaps
    %th
    %th
    %th

  - @locations.each do |location|
    %tr
      %td= location.zip_code
      %td= location.lat_long
      %td= location.street
      %td= location.latitude
      %td= location.longitude
      %td= location.gmaps
      %td= link_to 'Show', location
      %td= link_to 'Edit', edit_location_path(location)
      %td= link_to 'Destroy', location, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Location', new_location_path

app/views/locations/new.html.haml
%h1 New location

= render 'form'

= link_to 'Back', locations_path

app/views/locations/show.html.haml
%p#notice= notice

%p
  %b Zip code:
  = @location.zip_code
%p
  %b Lat long:
  = @location.lat_long
%p
  %b Street:
  = @location.street
%p
  %b Latitude:
  = @location.latitude
%p
  %b Longitude:
  = @location.longitude
%p
  %b Gmaps:
  = @location.gmaps

= link_to 'Edit', edit_location_path(@location)
\|
= link_to 'Back', locations_path

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :dispatch_on %><br>
    <%= f.text_field :dispatch_on %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br>
    <%= f.text_field :ip_address %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :number_id %><br>
    <%= f.text_field :number_id %>
  </div>
  <div class="field">
    <%= f.label :address_id %><br>
    <%= f.text_field :address_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Dispatch on</th>
      <th>Ip address</th>
      <th>Text</th>
      <th>User</th>
      <th>Num</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.category %></td>
        <td><%= message.dispatch_on %></td>
        <td><%= message.ip_address %></td>
        <td><%= message.text %></td>
        <td><%= message.user_id %></td>
        <td><%= message.num_id %></td>
        <td><%= message.address_id %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @message.category %>
</p>

<p>
  <strong>Dispatch on:</strong>
  <%= @message.dispatch_on %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @message.ip_address %>
</p>

<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user_id %>
</p>

<p>
  <strong>Num:</strong>
  <%= @message.num_id %>
</p>

<p>
  <strong>Address:</strong>
  <%= @message.address_id %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/numbers/_form.html.erb
<%= form_for(@number) do |f| %>
  <% if @number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@number.errors.count, "error") %> prohibited this number from being saved:</h2>

      <ul>
      <% @number.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :message_id %><br>
    <%= f.number_field :message_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/numbers/edit.html.erb
<h1>Editing number</h1>

<%= render 'form' %>

<%= link_to 'Show', @number %> |
<%= link_to 'Back', numbers_path %>

app/views/numbers/index.html.erb
<h1>Listing numbers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Phone number</th>
      <th>Message</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @numbers.each do |number| %>
      <tr>
        <td><%= number.user_id %></td>
        <td><%= number.phone_number %></td>
        <td><%= number.message_id %></td>
        <td><%= link_to 'Show', number %></td>
        <td><%= link_to 'Edit', edit_number_path(number) %></td>
        <td><%= link_to 'Destroy', number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Number', new_number_path %>

app/views/numbers/new.html.erb
<h1>New number</h1>

<%= render 'form' %>

<%= link_to 'Back', numbers_path %>

app/views/numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @number.user_id %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @number.phone_number %>
</p>

<p>
  <strong>Message:</strong>
  <%= @number.message_id %>
</p>

<%= link_to 'Edit', edit_number_path(@number) %> |
<%= link_to 'Back', numbers_path %>